[lab 2] Update BC4 instructions/scripts
COMS30117-Deep-Learning/labsheets pull request #4
Opened 2022-10-03 16:11 UTC by ktw361

2022-10-06 20:08 UTC, mwray commented
Could you add the stdout and stderr args as in [be24629](https://github.com/COMSM0045-Applied-Deep-Learning/labsheets/commit/be2462931e1447675d104d166bfaa23fad04cd8b) for the relevant bits?

2022-10-06 20:10 UTC, mwray requested changes
Could you add the stdout and stderr args to the relevant places as in [855fcab](https://github.com/COMSM0045-Applied-Deep-Learning/labsheets/commit/855fcab62195c21653ed9789b7a09c47ffd05b84)?

2022-10-10 16:24 UTC, ktw361 commented
> Could you add the stdout and stderr args to the relevant places as in [855fcab](https://github.com/COMSM0045-Applied-Deep-Learning/labsheets/commit/855fcab62195c21653ed9789b7a09c47ffd05b84)?

Just added the std out/err args

2022-10-11 10:13 UTC, mwray approved these changes

2022-10-11 10:14 UTC, merged